# Generated by Django 4.1.2 on 2022-10-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="link",
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
