# Generated by Django 4.1.2 on 2022-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_feeditem_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeditem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
